### ISSUE TITLE
Responsive styles for header + navigation

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#10]
placeholder from #8, will update once designs exist

**Comment by ryelle** [comment]
From @melchoyce  

> Can we replace the visible "primary menu" text with a hamburger instead?

But what should it do when it opens?

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/57116116-ea067080-6d07-11e9-898c-962525b85e4d.png)

https://drive.google.com/open?id=1zRtZHEXPbj2nz9vp9p4-lwNA0zHy-9uy
