### ISSUE TITLE
Homepage (first iteration)

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#14]
@melchoyce has handed off this first iteration of the homepage – design will be ongoing as the homepage evolves, but this is good to build. The majority of the page is gutenberg page content- lots of Media & Text blocks :) 

![](https://user-images.githubusercontent.com/541093/56321982-d834a300-6135-11e9-8ff9-2b8a56bcc9c0.png)

**Comment by ryelle** [comment]
I've now created a bunch of Blocks issues, so the focus of this issue should be on the header widgets/structure.

**Comment by ryelle** [comment]
This section will be a list block with a special class (`has-fancy-style` 😆):
 
![Screen Shot 2019-04-17 at 5 55 28 PM](https://user-images.githubusercontent.com/541093/56323513-18962000-613a-11e9-9449-5513e6dd078d.png)

**Comment by alpinealex** [comment]
@yingles - I would be happy to help out with this tomorrow. Can you outline the specific things you'd like help with?

**Comment by ryelle** [comment]
@alpinealex The header widgets are "done" in PRs now, you could review #27 & #30. The rest of the page content here is styled blocks, so any of the unassigned "Block: [thing]" issues are good to grab.

**Comment by yingles** [comment]
Think we just need the fancy list to close out the homepage https://github.com/wcus/wcus-2019/issues/14#issuecomment-484276569.

@alpinealex could be good to grab to knock out if you have time.
