### ISSUE TITLE
Block: Latest Posts

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#17]
Grid style of Latest Posts block:

![Blocks: Latest Posts](https://user-images.githubusercontent.com/541093/56322550-59d90080-6137-11e9-9893-4eebb8e93339.jpg)

@melchoyce Will the list view ever be used?

**Comment by melchoyce** [comment]
Probably not, but I'll design a list view just in case.

**Comment by ryelle** [comment]
OK - going to leave this as needs dev, so at least the grid-view can be built. We can always create another issue for list-view.
