### ISSUE TITLE
Block: Media & Text

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#18]
Media & Text block will have a background color behind the text. @melchoyce What color should be default?

For now, assume the background colors will be hand-picked in the Custom Color section, since we can't change the default color palette.

![](https://user-images.githubusercontent.com/541093/56322629-960c6100-6137-11e9-8b3e-56786480dae2.jpg)

**Comment by melchoyce** [comment]
Let's default to blue.
