### ISSUE TITLE
Block: Pullquote & Quote

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#19]
3 styles of quotes:

- Pullquote block
- Quote block, large style
- Quote block, regular style

![Blocks: Quotes](https://user-images.githubusercontent.com/541093/56322906-4c704600-6138-11e9-90e9-81b4aa1855a5.jpg)

**Comment by yingles** [comment]
I pulled the SVGs from Sketch and uploaded them to wc-us.org.

https://wc-us.org/wp-content/uploads/2019/04/speech.svg
https://wc-us.org/wp-content/uploads/2019/04/quotes.svg
https://wc-us.org/wp-content/uploads/2019/04/text-bubble.svg
