### ISSUE TITLE
Footer design

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#2]
The footer will be made of widgets:

- Footer 1: Sponsors widget, HTML widget with a link to the sponsors page, with the class `cta-button` for button styling
- Footer 2: Subscribe widget
- Footer 3: 2 HTML widgets with text and social links
- Footer 4: A nav menu "Footer", an HTML widget with the "Proudly powered…" text

We'll hide the theme-provided `.site-info` to prevent duplicate text.

![image](https://user-images.githubusercontent.com/541093/54881818-729d1180-4e2a-11e9-889e-1b05043940a6.png)

@melchoyce – in trello you've got a design for the sponsors section called "sponsors shortcode", but did you mean widget? The sponsors shortcode is what's used on the sponsors page and usually has the sponsor blurb for each.

**Comment by melchoyce** [comment]
I was thinking we'd use the same design both in the footer, and in the Speakers page. On the speakers page, we'll hide everything but logo, and link off to the single speaker page, which will contain all the blurb.

**Comment by ryelle** [comment]
We should turn on widget visibility and hide the sponsors block on the Sponsors page, to prevent a double logo overload 😁

**Comment by melchoyce** [comment]
(Sponsor page will also exclude the "Learn More" button.)
