### ISSUE TITLE
Block: Separator

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#20]
![Blocks: Seperator](https://user-images.githubusercontent.com/541093/56323006-9527ff00-6138-11e9-8411-270e241d42ff.jpg)

@melchoyce Should this be used for all separator styles, or just the dots one? (There's also short line and wide line)

**Comment by kjellr** [comment]
This is what I'm thinking for the separators: 

![separators](https://user-images.githubusercontent.com/1202812/56362441-dad7dc80-61b7-11e9-8beb-68a45dc367a4.png)

The labels of the wide/dots ones are a little weird, but I think we're stuck with those names. The plain dotted line should definitely be the default, as it is the least intrusive. 

@melchoyce, what do you think of those?

**Comment by melchoyce** [comment]
Love 'em!

**Comment by kjellr** [comment]
Awesome, thanks. 

Here are SVGs for the sparkles used in the Wide and Dots variants: https://cloudup.com/c6iMr9Ru2dl
