### ISSUE TITLE
Single Post

### ISSUE THREAD

**Issue by melchoyce** [wcus/wcus-2019#28]
Would something like this work?

![image](https://user-images.githubusercontent.com/2846578/56768200-b2ce1780-677b-11e9-9064-e3ac29d95502.png)

**Comment by ryelle** [comment]
Thanks for posting this on GH 👍   gonna set it to unassigned though, since we've been using that as "I am working on this"

**Comment by kjellr** [comment]
This looks good, @melchoyce. Straightforward + simple. 👍 

A couple tiny bits of feedback: 

- Is that social section a block? They seem a little big. 
- The font size for the post meta at the bottom seems a little small. I'd also double check that it passes a contrast test with that size/color combo.

**Comment by melchoyce** [comment]
> Is that social section a block? They seem a little big.

It's a bunch of blocks combined: https://2019.us.wordcamp.org/2019/03/20/wordcamp-us-march-2019-update/

Would love some ideas here. We could potentially remove the text and just do columns with icons?

> The font size for the post meta at the bottom seems a little small. I'd also double check that it passes a contrast test with that size/color combo.

I'll bump up the size. The contrast ratio is 4.45, so we could definitely darken it a little.

Idea:

![image](https://user-images.githubusercontent.com/2846578/56820695-959c5600-681a-11e9-88c3-ec07ea9acf31.png)

**Comment by kjellr** [comment]
Both those changes look great. 👍

**Comment by melchoyce** [comment]
Awesome. I'll update these in the Sketch file in Drive. 

@kjellr Can I have you add `#747466` to the style guide?

**Comment by kjellr** [comment]
> @kjellr Can I have you add #747466 to the style guide?

Added!

**Comment by alpinealex** [comment]
@melchoyce - Can you point me in the direction of the "Sketch file in Drive" you mentioned? Thanks!

**Comment by melchoyce** [comment]
@alpinealex Are you on our Trello yet? https://trello.com/b/GU7Nruo4/web-and-design If not, ping me in Slack for an invite. In the meantime, you can find the sketch file here: https://drive.google.com/file/d/1zRtZHEXPbj2nz9vp9p4-lwNA0zHy-9uy/view?usp=sharing

**Comment by alpinealex** [comment]
@melchoyce - I'm in, thanks!
