### ISSUE TITLE
Interior page design

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#3]
Set up the structure for interior pages, ignoring featured images for now. 

- Create wavy blue header
- Add support for `.alignwide`

![Interior__No_Image](https://user-images.githubusercontent.com/541093/54940276-cda13800-4f00-11e9-8882-9f331c1397cc.png)

**Comment by melchoyce** [comment]
Coblocks has a nice wave:

`<svg class="divider--wavy" height="100%" viewBox="0 0 100 10" width="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="m42.19.65c2.26-.25 5.15.04 7.55.53 2.36.49 7.09 2.35 10.05 3.57 7.58 3.22 13.37 4.45 19.26 4.97 2.36.21 4.87.35 10.34-.25s10.62-2.56 10.62-2.56v-6.91h-100.01v3.03s7.2 3.26 15.84 3.05c3.92-.07 9.28-.67 13.4-2.24 2.12-.81 5.22-1.82 7.97-2.42 2.72-.63 3.95-.67 4.98-.77z" fill-rule="evenodd" transform="matrix(1 0 0 -1 0 10)"></path></svg>`
