### ISSUE TITLE
Latest Posts block has extra margin on small screen

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#34]
When the block is set to be `is-grid`, some extra margin gets added by Gutenberg. This sticks around in the small-screen layout, pushing it up to the edge.

@melchoyce Any other feedback on how to handle these blocks on small screens? The Media & Text is basically doing the same thing ATM, going edge-to-edge.

![Screen Shot 2019-04-27 at 1 49 12 PM](https://user-images.githubusercontent.com/541093/56853259-4e35c880-68f3-11e9-93ac-0d4ecd19426a.png)

**Comment by melchoyce** [comment]
Can we add the same margin to the left as well, so it's centered?
