### ISSUE TITLE
Single posts with multiple categories & tags are wonky

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#49]
which is weird, since I couldn't get categories to display on my local site in the first place.

<img width="665" alt="Screen Shot 2019-04-30 at 10 31 45 PM" src="https://user-images.githubusercontent.com/541093/57003891-ef44ad80-6b97-11e9-9a95-df70d447725f.png">

**Comment by brettshumaker** [comment]
> the issue is the entire section -- it shouldn't be in columns like that.

Is there design on how this section should look? I see that #28 had the design for single posts and I think it shows this section as having the categories and tags in "columns." Admittedly, not with as much space between them.

**Comment by ryelle** [comment]
no, i'm basically going off that mockup and knowing what @melchoyce  probably meant :) I think these things aren't meant to wrap, so in this example tags would be on the next line.

**Comment by brettshumaker** [comment]
Would something like this work? And should we now include the `folder` svg shown in the design on #28?

<img width="659" alt="Screen Shot 2019-05-01 at 11 35 39 AM" src="https://user-images.githubusercontent.com/1558827/57028794-a0356180-6c05-11e9-9dd8-453847f59963.png">

Also, these changes will affect the same section under posts on the archive pages, which also have a "column" for comment information. I could also drop the comment information down to a third row with maybe a "comment" svg icon?

<img width="658" alt="Screen Shot 2019-05-01 at 11 41 48 AM" src="https://user-images.githubusercontent.com/1558827/57028983-281b6b80-6c06-11e9-89d9-71c805eb9a5e.png">

**Comment by ryelle** [comment]
Yes, this should be the case everywhere there is footer meta. We can use `$icon-text` for the comments, and I've uploaded the folder to `https://wc-us.org/wp-content/uploads/2019/05/category.svg`
