### ISSUE TITLE
Alignment issue on social items

### ISSUE THREAD

**Issue by yingles** [wcus/wcus-2019#50]
Page: https://2019.us.wordcamp.org/2019/03/01/wordcamp-u-s-2019-timeline-save-the-date/

![image](https://user-images.githubusercontent.com/4986487/57003974-45155780-6b90-11e9-9437-bcc829f044ca.png)

**Comment by ryelle** [comment]
Posts should be using the Reusable Block "Social List" – I've updated that post to use it.

**Comment by brettshumaker** [comment]
Should this be marked as `solved`? Or should we go through existing posts and make sure the correct block is being used?

**Comment by ryelle** [comment]
Was waiting for a confirmation that this works as a solution

**Comment by yingles** [comment]
That makes sense to me. If we see it crop up we'll just need to remind people to use the reusable block.
