### ISSUE TITLE
Navigation: 3rd level menu items

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#59]
The parent item needs a different style (the right arrow, maybe):

![Screen Shot 2019-05-01 at 1 13 30 PM](https://user-images.githubusercontent.com/541093/57030530-fceb4900-6c12-11e9-97ac-e7076eacacea.png)

Alignment and maybe spacing needs to be tweaked on the 3rd level flyout– probably just move the 3rd level container up 15px?

![Screen Shot 2019-05-01 at 1 13 41 PM](https://user-images.githubusercontent.com/541093/57030532-fe1c7600-6c12-11e9-881f-b1be8721a800.png)

**Comment by melchoyce** [comment]
I'm wondering if we should just pop Hotel Block underneath Location and try to not have three levels of navigation anywhere

**Comment by ryelle** [comment]
Assuming this is the solution, I'm going to close this. We can revisit if we turn out to need a 3rd level after all.
