### ISSUE TITLE
Tighten space in primary navigation

### ISSUE THREAD

**Issue by melchoyce** [wcus/wcus-2019#64]
![image](https://user-images.githubusercontent.com/2846578/57044851-c74d5c80-6c20-11e9-8e31-400b1445ae6e.png)

- Change down icon to smaller chevron (https://cldup.com/hMssBo7QPv.svg)
- Only 10px of padding on left/right of navigation menu items

**Comment by melchoyce** [comment]
Ah, and we still need that custom class for signup

**Comment by ryelle** [comment]
We're using the same (arrow) SVG for the dropdown hovers, should that stay arrow or also be chevron now?

**Comment by melchoyce** [comment]
Let's use the chevron instead and rotate it.
