### ISSUE TITLE
Custom background colors not working

### ISSUE THREAD

**Issue by melchoyce** [wcus/wcus-2019#67]
See: https://2019.us.wordcamp.org/the-marriott-st-louis-grand-is-the-wcus-2019-official-hotel/
 
![image](https://user-images.githubusercontent.com/2846578/57048740-1a77dd00-6c2a-11e9-8a83-96f8915f2ce2.png)

![image](https://user-images.githubusercontent.com/2846578/57048760-2b285300-6c2a-11e9-9e9d-4125ca22a672.png)

**Comment by ryelle** [comment]
Did you try with any other colors? the light grey was mapped to the cream background color, so it's there but "invisible" – see https://github.com/wcus/wcus-2019/pull/31

**Comment by ryelle** [comment]
Do you want a proper light grey instead? just give me a hex 🙂

**Comment by melchoyce** [comment]
Ahhhh okay. I didn't make the page, so I'm not sure — I'll replace with a custom color instead.

**Comment by melchoyce** [comment]
(We should document this somehow)

**Comment by ryelle** [comment]
Agreed, opened #68 👍
