### ISSUE TITLE
Wide alignment not resizing videos

### ISSUE THREAD

**Issue by yingles** [wcus/wcus-2019#85]
Reported by @melchoyce on Slack. https://wcus.slack.com/archives/C9KMESY0H/p1559925802017700

![image](https://user-images.githubusercontent.com/4986487/59140638-16945480-8966-11e9-9ed2-b6fe61076e08.png)

**Comment by ryelle** [comment]
Patch posted at https://meta.trac.wordpress.org/ticket/4500 - will need to be merged on wordcamp.org, but it should "just work" once merged.

**Comment by ryelle** [comment]
The patch was committed to meta 3 weeks ago, we should be able to align-wide videos now. Closing, can re-open if this is still an issue.
