### ISSUE TITLE
Style Speakers block

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#86]
This is the speakers list block. It will be used for the `/speakers` page, but could also be used in posts for speaker announcements.

![image](https://user-images.githubusercontent.com/541093/60993110-d08f2f80-a31b-11e9-83e1-507d2706c4f2.png)

@melchoyce I'm assuming this is for the "grid" style– do you want a different style for list? Thinking of posts like the [speaker](https://2018.us.wordcamp.org/2018/09/21/wordcamp-us-2018-speakers-round-one/) [announcement](https://2018.us.wordcamp.org/2018/09/25/wordcamp-us-2018-speakers-round-2/) [rounds](https://2018.us.wordcamp.org/2018/10/10/wordcamp-us-2018-speakers-round-8/), which seem to be manually built last year, but could be select speakers from the block dropdown (or speaker groups, which, TIL)

**Comment by melchoyce** [comment]
Yeah, good question — I'll make a trello card for list styles.

**Comment by kjellr** [comment]
Here's a mockup for the list view. Essentially: Same sparkles around the person, the images are all in a left column, and the text content is top-aligned to the photo (This is relatively similar to a Media + Text block). 

![speakers-list](https://user-images.githubusercontent.com/1202812/61313736-168b3e00-a7c9-11e9-974a-ecae48aceb0d.png)
