### ISSUE TITLE
SVG hosting

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#9]
We have [a handful of SVGs](https://github.com/wcus/wcus-2019/tree/3bb6aec89ce8bdcb83bbb1599eb41fd3fec5c0d8/assets) used for various style elements, but we can't upload them to wordcamp.org. We need to find a place to upload them, then we can change the [locations in the sass variables](https://github.com/wcus/wcus-2019/blob/3bb6aec89ce8bdcb83bbb1599eb41fd3fec5c0d8/sass/abstracts/_assets.scss) to match.

@yingles @kcristiano I think we decided on the DO server, maybe with another domain name? I don't think I have access to that, so if one of you can pick up this PR that would be great 🙂

**Comment by yingles** [comment]
SVG hosting is up on Digital Ocean at wc-us.org. I'll add anyone that would like access to upload.

**Comment by yingles** [comment]
Updated URLs in PR #21
