### ISSUE TITLE
Style schedule

### ISSUE THREAD

**Issue by ryelle** [wcus/wcus-2019#90]
Style the schedule page. This uses the schedule shortcode.

![Full-width_schedule](https://user-images.githubusercontent.com/541093/60994471-97a48a00-a31e-11e9-96d7-9444638417fc.png)

@melchoyce What were you thinking with the three links at the top, anchor links to sections on the page, or separate pages for each day?

**Comment by ryelle** [comment]
The schedule shortcode has a breakpoint at 700px where it collapses into a single-column view. We might want to force that at a higher breakpoint, since we have more tracks than the average camp. If the developer on this task needs any feedback how this should handle responsively, ping @melchoyce.

**Comment by melchoyce** [comment]
> What were you thinking with the three links at the top, anchor links to sections on the page, or separate pages for each day?

Anchor links

re: higher breakpoint, I think we should try to force it around ~1000px tbh.

**Comment by ryelle** [comment]
Added in #93
